"""initial migration

Revision ID: 113bdeb89491
Revises: 
Create Date: 2024-01-21 22:52:48.547959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "113bdeb89491"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(
        op.f("ix_admin_users_id"), "admin_users", ["id"], unique=False
    )
    op.create_table(
        "payment_informations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_type", sa.String(), nullable=True),
        sa.Column("card_number", sa.String(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("cvv", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_informations_id"),
        "payment_informations",
        ["id"],
        unique=False,
    )
    op.create_table(
        "user_statuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("current_state", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("timestamp", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_statuses_id"), "user_statuses", ["id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dob", sa.Date(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("status_id", sa.Integer(), nullable=True),
        sa.Column("payment_info_id", sa.Integer(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["payment_info_id"],
            ["payment_informations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["user_statuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_user_statuses_id"), table_name="user_statuses")
    op.drop_table("user_statuses")
    op.drop_index(
        op.f("ix_payment_informations_id"), table_name="payment_informations"
    )
    op.drop_table("payment_informations")
    op.drop_index(op.f("ix_admin_users_id"), table_name="admin_users")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
