"""add distributor

Revision ID: a2157058840a
Revises: 0278f42a3bc1
Create Date: 2024-01-28 00:44:52.027791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a2157058840a"
down_revision: Union[str, None] = "0278f42a3bc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "distributors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("pricing_per_year", sa.String(), nullable=True),
        sa.Column("recommended", sa.Boolean(), nullable=True),
        sa.Column("paypal_support", sa.Boolean(), nullable=True),
        sa.Column("sepa_support", sa.Boolean(), nullable=True),
        sa.Column("commision", sa.String(), nullable=True),
        sa.Column("approval_time_no_days_on_avg", sa.Float(), nullable=True),
        sa.Column(
            "closes_account_on_copyright_strike", sa.Boolean(), nullable=True
        ),
        sa.Column("warns_on_excessive_streaming", sa.Boolean(), nullable=True),
        sa.Column("offers_label_accounts", sa.Boolean(), nullable=True),
        sa.Column("browser_details_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["browser_details_id"],
            ["browser_connection_details.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_distributors_id"), "distributors", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_distributors_id"), table_name="distributors")
    op.drop_table("distributors")
    # ### end Alembic commands ###
