"""changed foreign keys location for user

Revision ID: b6128982a01f
Revises: ef8f0cc535b9
Create Date: 2024-01-29 12:27:54.366665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6128982a01f"
down_revision: Union[str, None] = "ef8f0cc535b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payment_informations",
        sa.Column("user_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None, "payment_informations", "users", ["user_id"], ["id"]
    )
    op.add_column(
        "user_statuses", sa.Column("user_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "user_statuses", "users", ["user_id"], ["id"])
    op.drop_constraint(
        "users_payment_info_id_fkey", "users", type_="foreignkey"
    )
    op.drop_constraint("users_status_id_fkey", "users", type_="foreignkey")
    op.drop_column("users", "status_id")
    op.drop_column("users", "payment_info_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "payment_info_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "status_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "users_status_id_fkey", "users", "user_statuses", ["status_id"], ["id"]
    )
    op.create_foreign_key(
        "users_payment_info_id_fkey",
        "users",
        "payment_informations",
        ["payment_info_id"],
        ["id"],
    )
    op.drop_constraint(None, "user_statuses", type_="foreignkey")
    op.drop_column("user_statuses", "user_id")
    op.drop_constraint(None, "payment_informations", type_="foreignkey")
    op.drop_column("payment_informations", "user_id")
    # ### end Alembic commands ###
